export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const SET_CITY_VALUE = 'SET_CITY_VALUE';
export const SET_ERROR_TEXT = 'SET_ERROR_TEXT';
export const SET_FORECAST_PERIOD = 'SET_FORECAST_PERIOD';
export const REQUEST_FORECAST = 'REQUEST_FORECAST';
export const RECEIVE_FORECAST = 'RECEIVE_FORECAST';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';